user_index:
    path:     /user/list
    defaults: { _controller: "CABlogBundle:User:index" }
    methods:  GET
    
user_new:
    path:     /register
    defaults: { _controller: "CABlogBundle:User:new" }
    methods:  [GET, POST]

user_show:
    path:     /user/{id}/show
    defaults: { _controller: "CABlogBundle:User:show" }
    methods:  GET


user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "CABlogBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "CABlogBundle:User:delete" }
    methods:  DELETE

user_posts:
    path:     /user/{id}
    defaults: { _controller: "CABlogBundle:User:posts" }
    methods:  GET
