CA\BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: CA\BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '100'
        content:
            type: text
        created:
            type: datetime
        updated:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
    manyToOne:
         user:
              targetEntity: User
              inversedBy: posts
              joinColumn:
                   name: user_id
                   referencedColumnName: id
                   onDelete: 'SET NULL'
