CA\BlogBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CA\BlogBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '50'
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        roles:
            type: array
    lifecycleCallbacks: {  }
    oneToMany:
         posts:
              targetEntity: Post
              mappedBy: user
