# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    providers:
         our_db_provider:
            entity:
                class: CABlogBundle:User
                property: username

    encoders:
        CA\BlogBundle\Entity\User: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            remember_me:
                 secret: '%secret%'
                 lifetime: 604800 # 1 week in secs
                 path: /
            provider: our_db_provider
            # activate different ways to authenticate

            anonymous: ~
            form_login:
                 login_path: login
                 check_path: login
            logout:
                path: /logout
                target: /login

    access_control:
         - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/user/[0-9]+/edit$: roles: ROLE_ADMIN }
         - { path: ^/user/[0-9]+/delete$: roles: ROLE_ADMIN }
         - { path: /edit$, roles: [ROLE_BLOGGER, ROLE_ADMIN] }
         - { path: /delete$, roles: [ROLE_ADMIN] }



            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate


            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
