ca_blog_post:
    resource: "@CABlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

ca_blog_user:
    resource: "@CABlogBundle/Resources/config/routing/user.yml"

ca_blog_homepage:
    path:     /
    defaults: { _controller: CABlogBundle:Blog:index }

index:
    path:     /index
    defaults: { _controller: CABlogBundle:Blog:index }

login:
    path:     /login
    defaults: { _controller: CABlogBundle:Session:login }  

logout:
     path: /logout
